### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jonasstein** [vain/sgopherd#2]
Hi, thank you for your software. We distribute it on Gentoo Linux.
It ships with a very unique license, which is not ideal for the open source community. 

The best for the user would be if he can see, that all his programs are covered by very few licenses, 
say 400 tools with BSD-2 and 900 tools GPL-3. 
We have to read and evaluate each license when we distribute software and the same happens for the user or site administrator.
At the moment we distribute software with **more than 700 different licenses**. It would be great, if you could adopt to one of the famous free software licenses. I think you would have no disadvantage and it would help the community a lot. 
Ideal would be a bump of the version number for the license change, and a note in the README, so that it is clear to everyone.

Here are some useful links:
https://en.wikipedia.org/wiki/License_proliferation
https://www.gnu.org/licenses/license-recommendations.en.html
https://choosealicense.com/
https://opensource.org/licenses/category

If you want to invite users to share a coffee, pizza, beer with you, or spend money to a special ngo, I suggest to add a note in the --info --license text or the man/help or documentation page of the software, but not as part of the license.

Thank you! JS

**Comment by vain** [comment]
Yes, agreed. It was probably not the best choice. I'll look into it this weekend.

**Comment by vain** [comment]
Alright, I think I'll relicense under the [MIT license](https://choosealicense.com/licenses/mit/).

Software licenses are a minefield and make my head hurt, so there might be corner cases I have not considered: If, for some reason, you'd advise against choosing this particular license, because it doesn't address the issues you've mentioned, please let me know. But since it appears to be the most widely used license alongside GPL, I believe it's a good choice. (And, of course, it reflects my intentions.)

Thanks!

**Comment by jonasstein** [comment]
That is great news. Thank you for your support. Ideal would be a change of the version number with the new license. Then it is clear for everyone.

**Comment by vain** [comment]
Done. :-)
